// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0xNsrmP8eStHu9DsqZ20UwjgfFBRBkV8',
    appId: '1:847162939973:web:8db6fe9dfa58f25c6aa12c',
    messagingSenderId: '847162939973',
    projectId: 'marketplace-f7a51',
    authDomain: 'marketplace-f7a51.firebaseapp.com',
    storageBucket: 'marketplace-f7a51.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXvSRvIDiPIdltk0Te9WBDxXPWlV3Gf2g',
    appId: '1:847162939973:android:f285ea72fe6b70b46aa12c',
    messagingSenderId: '847162939973',
    projectId: 'marketplace-f7a51',
    storageBucket: 'marketplace-f7a51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ6LWzuARofhTfPYJigfP5nPzC9MsGv2s',
    appId: '1:847162939973:ios:dc263a29c818335a6aa12c',
    messagingSenderId: '847162939973',
    projectId: 'marketplace-f7a51',
    storageBucket: 'marketplace-f7a51.appspot.com',
    iosClientId: '847162939973-ovj0ut12j9edojgqi6kbmuk13eb8kidc.apps.googleusercontent.com',
    iosBundleId: 'com.example.learn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ6LWzuARofhTfPYJigfP5nPzC9MsGv2s',
    appId: '1:847162939973:ios:dc263a29c818335a6aa12c',
    messagingSenderId: '847162939973',
    projectId: 'marketplace-f7a51',
    storageBucket: 'marketplace-f7a51.appspot.com',
    iosClientId: '847162939973-ovj0ut12j9edojgqi6kbmuk13eb8kidc.apps.googleusercontent.com',
    iosBundleId: 'com.example.learn',
  );
}
